name: K6 Browser Performance Tests
on:
  push:
 
jobs:
  performance-test:
    runs-on: ubuntu-latest
    env:
      K6_BROWSER_ENABLED: true  
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install Chrome dependencies
        if: runner.os == 'Linux'
        run: "${GITHUB_WORKSPACE}/.github/bin/install_chrome_deps_linux.sh"
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Chrome version
        if: runner.os != 'Windows'
        run: chrome --version
      - name: Chrome version
        if: runner.os == 'Windows'
        shell: pwsh
        # chrome --version doesn't work on Windows :-/
        # See https://bugs.chromium.org/p/chromium/issues/detail?id=158372
        run: (get-command chrome.exe).Version
   

      - name: Run browser k6 test
        uses: grafana/k6-action@v0.3.0
        with:
         filename: browserTest.js

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-browser-report-summary
          path: TestSummaryReport.html


      - name: Run k6 test on Lambda Test
        uses: grafana/k6-action@v0.3.0
        with:
         filename: loginTest.js


      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-browser-report-summary
          path: TestReport.html


    
