name: K6 Browser Performance Tests1
on:
  push:
 
jobs:
  performance-test:
    runs-on: ubuntu-latest
    env:
      K6_BROWSER_ENABLED: true  

   
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
        
     
      - name: Install Chrome and Chromedriver
        uses: browser-actions/setup-chrome@v1
      
      - name: Build the Docker image
        run: docker build -t browser-k6 -f Dockerfile .
        
     

      - name: Run k6 test on Lambda Test
        uses: grafana/k6-action@v0.3.0
        with:
         filename: loginTest.js


      


    
